# Generated by Django 4.0 on 2022-01-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ToDoItemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('toDoItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.todoitem')),
            ],
        ),
    ]
