# Generated by Django 4.0 on 2022-01-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todoitem_completedat_todoitemfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='notes',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
    ]
