# Generated by Django 4.0 on 2022-01-20 08:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todoitem_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitemfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models.user_directory_path),
        ),
    ]
